name: DVC Workflow

on:
  pull_request:
    branches:
    - main
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        make dev_requirements
        pip list

    - name: Pull data
      run: |
        dvc pull --no-run-cache

    - name: Check data statistics
      run: |
        python dataset_statistics.py
