name: Unit Tests

on:
  push:
    branches:
      - georgia
  pull_request:
    branches:
      - georgia

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt

      - name: Setup DVC and Cache
        uses: actions/composite@v2
        steps:
          - uses: iterative/setup-dvc@v1
          - uses: actions/cache@v3
            with:
              path: ~/.dvc/cache
              key: ${{ runner.os }}-dvc-${{ hashFiles('dvc.lock') }}
              restore-keys:
                - ${{ runner.os }}-dvc-

      - name: Get data
        run: dvc pull

      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m
